repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.100.0
  hooks:
    - id: terraform_fmt
      args:
        - --hook-config=--retry-once-with-cleanup=true
        - --args=-write=true
        - --args=-recursive=false # should be returned to true after solving issues with examples dependencies (vpc module in TF registry)
    - id: terraform_docs
      args:
        - --hook-config=--add-to-existing-file=true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
