name: "Terraform-Test"
on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches: [main, develop, release/*]
    types: [opened, labeled, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  terraform-test:
    name: "Terraform Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_INPUT: false

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Test
        if: github.event_name == 'pull_request'
        id: test
        run: terraform test
