name: "Terraform"

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches: [main, develop, release/*]
    types: [opened, labeled, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  terraform:
    uses: jivygroup/om2-github-workflows/.github/workflows/terraform.yaml@main
    secrets: inherit
    with:
      workspace-name: om2-autotest-vpc-peering
      working-directory: examples/standard-connection
